### ISSUE TITLE
instancing no longer mapped properly in 2018.22800

### ISSUE THREAD

**Issue by mickeyvanolst** [mir-lab/touchdesigner-instancing-examples#1]
Sadly the texture is no longer correctly mapped, see Step 3 of pixelMappingGeometry

<img width="522" alt="capture" src="https://user-images.githubusercontent.com/1071097/39968841-a4838e94-56d3-11e8-9c41-88c1de0e8f65.PNG">

**Comment by raganmd** [comment]
hey @popsure can you tell me which version of Touch and OS you're running this example on? In the latest build 2018.22800 on a Windows10 box I see this in `/pixelMappingGeometry/step3`:
![pixelmappinggeometry-step3](https://user-images.githubusercontent.com/11582808/39978850-abc0d602-56f7-11e8-9e4c-08f942427cba.PNG)

**Comment by mickeyvanolst** [comment]
Just checked again, both on MacOS and Windows 10 (Home v. 1803) I get the same result as the picture I posted, both are on the latest versions of TD and their OS. I ran into it when I was following your tutorial on youtube and ran into incorrectly mapped vertices, after checking the github repo I ran into the same result with your project file.

**Comment by mickeyvanolst** [comment]
![image](https://user-images.githubusercontent.com/1071097/39987547-5fad8062-5765-11e8-9b63-af79ee9f8fb5.png)

Texture in process seems to look fine

**Comment by raganmd** [comment]
I think this is resolved now with 289fa8e658f84ae933257669ec228bfe760ab2b3

@popsure Can you confirm that you were using a non-commercial license on Windows and Mac? The size of the constant TOP would have exceeded the non-commercial resolution limit, which would present as incorrectly mapped pixel values. I've updated the dimensions for the example to be non-commercial save, so it should now work as expected.

**Comment by mickeyvanolst** [comment]
Yes thats right, makes total sense!

Also good perhaps to make the change with the other steps, but it definitely did the trick.
